export const FORMATS = [
  { value: 'commander', label: 'Commander / EDH' },
  { value: 'standard', label: 'Standard' },
  { value: 'modern', label: 'Modern' },
  { value: 'pioneer', label: 'Pioneer' },
  { value: 'legacy', label: 'Legacy' },
  { value: 'vintage', label: 'Vintage' },
  { value: 'pauper', label: 'Pauper' },
  { value: 'other', label: 'Other' },
] as const

export const ARCHETYPES = [
  '+1/+1 Counters',
  'Aggro',
  'Alternate Win Condition',
  'Aristocrats',
  'Artifacts Matter',
  'Big Mana',
  'Blink / Flicker',
  'Burn',
  'Chaos',
  'Clones / Copy',
  'Combo',
  'Commander Damage',
  'Control',
  'Discard',
  'Dredge',
  'Enchantress',
  'Equipment / Auras',
  'Food / Clue / Blood Tokens',
  'Goodstuff',
  'Graveyard Value',
  'Group Hug',
  'Group Slug',
  'Infect / Poison',
  'Land Destruction',
  'Landfall',
  'Lands Matter',
  'Lifedrain',
  'Lifegain',
  'Midrange',
  'Mill',
  'Pillow Fort',
  'Politics',
  'Prison',
  'Ramp',
  'Reanimator',
  'Recursion',
  'Self-Mill',
  'Spellslinger',
  'Stax',
  'Storm',
  'Superfriends',
  'Tax',
  'Tempo',
  'Theft',
  'Tokens',
  'Tribal',
  'Treasure',
  'Vehicles',
  'Voltron',
] as const

export const POWER_LEVELS = [
  { value: 'casual', label: 'Casual' },
  { value: 'precon', label: 'Precon' },
  { value: 'mid', label: 'Mid-power' },
  { value: 'high', label: 'High-power' },
  { value: 'cedh', label: 'cEDH' },
] as const

export const MTG_COLORS = [
  { value: 'W', label: 'White' },
  { value: 'U', label: 'Blue' },
  { value: 'B', label: 'Black' },
  { value: 'R', label: 'Red' },
  { value: 'G', label: 'Green' },
] as const

export const SORT_OPTIONS = [
  { value: 'recent', label: 'Recently added' },
  { value: 'value_asc', label: 'Price: low to high' },
  { value: 'value_desc', label: 'Price: high to low' },
  { value: 'power_asc', label: 'Power: low to high' },
  { value: 'power_desc', label: 'Power: high to low' },
] as const

export const PROVINCES = [
  { value: 'AB', label: 'Alberta' },
  { value: 'BC', label: 'British Columbia' },
  { value: 'MB', label: 'Manitoba' },
  { value: 'NB', label: 'New Brunswick' },
  { value: 'NL', label: 'Newfoundland and Labrador' },
  { value: 'NS', label: 'Nova Scotia' },
  { value: 'NT', label: 'Northwest Territories' },
  { value: 'NU', label: 'Nunavut' },
  { value: 'ON', label: 'Ontario' },
  { value: 'PE', label: 'Prince Edward Island' },
  { value: 'QC', label: 'Quebec' },
  { value: 'SK', label: 'Saskatchewan' },
  { value: 'YT', label: 'Yukon' },
] as const
